### ISSUE TITLE
Error new variable 3d download

### ISSUE THREAD

**Issue by pinuzzz** [guidocioni/icon_d2#4]
Hi Guido,
I tried to add in the copy_data.run file in the 3D variables section a new variable to download “tke”: the file is present in the DWD server with the extension grib2.bz2 like the other  , but I still get the error “no such file or directory”
`cdo    merge: Open failed on >icon-d2_germany_regular-lat-lon_pressure-level_2024081806_*_tke.grib2<
              No such file or directory`

Any idea why this happens?
Thanks

**Comment by guidocioni** [comment]
> Hi Guido, I tried to add in the copy_data.run file in the 3D variables section a new variable to download “tke”: the file is present in the DWD server with the extension grib2.bz2 like the other , but I still get the error “no such file or directory” `cdo merge: Open failed on >icon-d2_germany_regular-lat-lon_pressure-level_2024081806_*_tke.grib2< No such file or directory`
> 
> Any idea why this happens? Thanks

Did you have a closer look at what the function does? 

https://github.com/guidocioni/icon_d2/blob/444be060ff4c22d695817600cc5873881b005d10/functions_download_dwd.sh#L35-L47

This is downloading pressure levels data. `tke` only has data on model levels (https://opendata.dwd.de/weather/nwp/icon-d2/grib/00/tke/), so it fails to find those files. 

You can write an equivalent bash function to download data on model levels and then interpolate on pressure levels (if that's your need).

**Comment by pinuzzz** [comment]
I understood
Thank you Guido always helpful!
Have a nice day
